// flow-typed signature: e146a7a68c262e02d84eb3777c1e823a
// flow-typed version: <<STUB>>/babel-node_v0.0.1-security/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-node' {
  declare module.exports: any;
}
