// flow-typed signature: e39881c1b314f73cc0c849ed20f7b9d8
// flow-typed version: <<STUB>>/color-shift_vgit+https://github.com/tuomashatakka/color-shift.git/flow_v0.124.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-shift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-shift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-shift/src/color-conversion' {
  declare module.exports: any;
}

declare module 'color-shift/src/color-functions' {
  declare module.exports: any;
}

declare module 'color-shift/src/Color' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-shift/src/color-conversion.js' {
  declare module.exports: $Exports<'color-shift/src/color-conversion'>;
}
declare module 'color-shift/src/color-functions.js' {
  declare module.exports: $Exports<'color-shift/src/color-functions'>;
}
declare module 'color-shift/src/Color.js' {
  declare module.exports: $Exports<'color-shift/src/Color'>;
}
